#!/bin/bash

##################################################
##					VARIABLES					##
##	  Set All Variables Before Using Script		##
##################################################
# BASE_LAN_IP="192.168.1"

if [ -z $BASE_LAN_IP ];then
		echo -e "########################################################"
		echo -e "# !! PLEASE SET VARIABLES IN SCRIPT BEFORE RUNNING. !! #"
		echo -e "########################################################"
		exit 1
fi
#ping all possible IPs on network
for i in {1..249};do
	ping -c 1 -n -q -r -t 1 -s 1 -W 1 $BASE_LAN_IP.$i > /dev/null &
done

echo
ARG01=$(if [[ -z $1 ]];then echo "running";else echo "$1";fi) 
#get list of vms
for name in $(virsh list | grep -i "$ARG01" | awk '{print $2}');do
#print all vms and their ip and mac address
	printf "$name: "
	arp -an | grep "$(virsh dumpxml $name | grep "mac address"| sed "s/.*'\(.*\)'.*/\1/g")" | awk '{print $2," -- ",$4}' | tr -d '()'
done

echo
