#!/bin/bash

####################################################
##					VARIABLES					  ##
##	  Set All Variables Before Using Script		  ##
## This script is intended to be run on the guest ##
####################################################
# DOMAIN="DOMAIN.LOCAL.OR.NOTLOCAL"

if [ -z $DOMAIN ];then
		echo -e "########################################################"
		echo -e "# !! PLEASE SET VARIABLES IN SCRIPT BEFORE RUNNING. !! #"
		echo -e "########################################################"
		exit 1
fi

# Get hostname for new VM
read -p "New Hostname: " NEW_HOST

# Set hostname on Guest
OLD_HOST=$(cat /etc/hostname)
echo "Removing Old Hostname Line from /etc/hosts"
sed -i '/'$OLD_HOST'$/ d' /etc/hosts
echo "Ammending New Hostname Line to /etc/hosts"
echo -e "127.0.1.1\t$NEW_HOST.$DOMAIN\t$NEW_HOST" >> /etc/hosts
cat /etc/hosts
echo "Setting Hostname in /etc/hostname"
echo "$NEW_HOST" > /etc/hostname
cat /etc/hostname
echo "Reboot Machine to finish."
