#!/bin/bash

# Get hostname for new VM
if [[ -z $1 ]];then
read -p "New Hostname: " NEW_HOST
else
NEW_HOST="$1"
fi

# Set hostname on Guest
OLD_HOST=$(cat /etc/hostname)
echo -e "Ammending New Hostname Line to /etc/hosts\n"
sed -i 's/'$OLD_HOST'/'$NEW_HOST'/g' /etc/hosts
echo "cat /etc/hosts";cat /etc/hosts
echo -e "\nSetting Hostname in /etc/hostname\n"
echo "$NEW_HOST" > /etc/hostname
echo "cat /etc/hostname";cat /etc/hostname
echo "Reboot Machine to finish."
